In [13]:
import tensorflow as tf
import numpy as np
print("Tensorflow version: ", tf.__version__)

Tensorflow version:  2.6.2


In [14]:
mnist = tf.keras.datasets.mnist

In [15]:
x = (x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [16]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [17]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.23127165, -0.10451353,  0.04111265,  1.1097527 ,  0.8315848 ,
         0.24059418, -0.17737694, -0.3035525 ,  0.42773744, -0.07689789]],
      dtype=float32)

In [18]:
tf.nn.softmax(predictions).numpy()

array([[0.09104894, 0.06507966, 0.07528178, 0.21917668, 0.16595395,
        0.09190171, 0.06050636, 0.05333395, 0.1108151 , 0.06690191]],
      dtype=float32)

In [20]:
#Definicja funkcji straty

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [21]:
#prawdopodobieństwo

loss_fn(y_train[:1], predictions).numpy()

2.3870356

In [22]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [23]:
#trenowanie modelu 
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3022 - accuracy: 0.9124
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1488 - accuracy: 0.9557
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1124 - accuracy: 0.9663
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0926 - accuracy: 0.9718
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0780 - accuracy: 0.9754


In [27]:
#sprawdzenie wydajności modelu
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0782 - accuracy: 0.9753


[0.07820191234350204, 0.9753000140190125]

In [29]:
probality_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [30]:
probality_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1975821e-07, 1.8909814e-08, 2.0262898e-05, 1.5716397e-04,
        4.8545040e-10, 3.0487868e-08, 1.8708390e-14, 9.9980336e-01,
        3.0706572e-06, 1.6012222e-05],
       [1.4454627e-06, 7.5008243e-06, 9.9988782e-01, 3.8016409e-05,
        2.7441958e-14, 3.8344402e-05, 2.1392407e-07, 1.5450438e-13,
        2.6564572e-05, 2.7956475e-14],
       [2.5546782e-08, 9.9951875e-01, 5.6896246e-05, 1.4525411e-05,
        3.3462729e-05, 6.6089451e-06, 8.5209813e-06, 3.1326915e-04,
        4.7973030e-05, 6.7954488e-08],
       [9.9988091e-01, 2.7394509e-09, 6.0843231e-06, 2.8122958e-08,
        1.4143899e-07, 3.7995625e-07, 1.0645807e-04, 1.7544353e-06,
        2.0019300e-08, 4.3159748e-06],
       [4.7005705e-07, 1.6009564e-09, 9.6385634e-07, 2.8153249e-08,
        9.9764711e-01, 2.3697357e-06, 3.4215923e-06, 7.6663062e-05,
        1.5664669e-06, 2.2673884e-03]], dtype=float32)>