In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd
import numpy as np

In [5]:
import tensorflow as tf
from tensorflow.keras import layers

In [6]:
abalone_train = pd.read_csv(
    "https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
    names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight",
           "Viscera weight", "Shell weight", "Age"])

In [7]:
abalone_train.head()


Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.435     0.335   0.110         0.334          0.1355          0.0775   
1   0.585     0.450   0.125         0.874          0.3545          0.2075   
2   0.655     0.510   0.160         1.092          0.3960          0.2825   
3   0.545     0.425   0.125         0.768          0.2940          0.1495   
4   0.545     0.420   0.130         0.879          0.3740          0.1695   

   Shell weight  Age  
0        0.0965    7  
1        0.2250    6  
2        0.3700   14  
3        0.2600   16  
4        0.2300   13

In [8]:
abolone_features = abalone_train.copy()
abolone_labels = abalone_train.pop('Age')

In [9]:
abolone_features = np.array(abolone_features)
abolone_features

array([[ 0.435 ,  0.335 ,  0.11  , ...,  0.0775,  0.0965,  7.    ],
       [ 0.585 ,  0.45  ,  0.125 , ...,  0.2075,  0.225 ,  6.    ],
       [ 0.655 ,  0.51  ,  0.16  , ...,  0.2825,  0.37  , 14.    ],
       ...,
       [ 0.53  ,  0.42  ,  0.13  , ...,  0.167 ,  0.249 , 11.    ],
       [ 0.395 ,  0.315 ,  0.105 , ...,  0.091 ,  0.1195, 16.    ],
       [ 0.45  ,  0.355 ,  0.12  , ...,  0.0665,  0.16  , 19.    ]])

In [10]:
#tworzenie modelu do trenowania
abalone_model = tf.keras.Sequential([
    layers.Dense(64),
    layers.Dense(1)
])

abalone_model.compile(loss= tf.keras.losses.MeanSquaredError(),
                      optimizer = tf.optimizers.Adam())

In [11]:
abalone_model.fit(abolone_features, abolone_labels, epochs=10)

Epoch 1/10
104/104 [==============================] - 0s 1ms/step - loss: 17.3825
Epoch 2/10
104/104 [==============================] - 0s 1ms/step - loss: 0.1173
Epoch 3/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0864
Epoch 4/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0602
Epoch 5/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0402
Epoch 6/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0267
Epoch 7/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0177
Epoch 8/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0120
Epoch 9/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0082
Epoch 10/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0057


In [12]:
abolone_features

array([[ 0.435 ,  0.335 ,  0.11  , ...,  0.0775,  0.0965,  7.    ],
       [ 0.585 ,  0.45  ,  0.125 , ...,  0.2075,  0.225 ,  6.    ],
       [ 0.655 ,  0.51  ,  0.16  , ...,  0.2825,  0.37  , 14.    ],
       ...,
       [ 0.53  ,  0.42  ,  0.13  , ...,  0.167 ,  0.249 , 11.    ],
       [ 0.395 ,  0.315 ,  0.105 , ...,  0.091 ,  0.1195, 16.    ],
       [ 0.45  ,  0.355 ,  0.12  , ...,  0.0665,  0.16  , 19.    ]])

In [13]:
normalize = layers.Normalization()

In [14]:
normalize.adapt(abolone_features)

In [15]:
norm_abalone_model = tf.keras.Sequential([
    normalize,
    layers.Dense(64),
    layers.Dense(1)
])

norm_abalone_model.compile(loss=tf.losses.MeanSquaredError(),
                           optimizer = tf.optimizers.Adam())
abolone_features

norm_abalone_model.fit(abolone_features, abolone_labels, epochs=10)

Epoch 1/10
104/104 [==============================] - 0s 1ms/step - loss: 90.7429
Epoch 2/10
104/104 [==============================] - 0s 1ms/step - loss: 52.2393
Epoch 3/10
104/104 [==============================] - 0s 1ms/step - loss: 14.1942
Epoch 4/10
104/104 [==============================] - 0s 1ms/step - loss: 1.2271
Epoch 5/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0343
Epoch 6/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0038
Epoch 7/10
104/104 [==============================] - 0s 1ms/step - loss: 0.0017
Epoch 8/10
104/104 [==============================] - 0s 1ms/step - loss: 9.6082e-04
Epoch 9/10
104/104 [==============================] - 0s 1ms/step - loss: 6.6872e-04
Epoch 10/10
104/104 [==============================] - 0s 1ms/step - loss: 5.1302e-04


In [16]:
#titanic sample
titanic = pd.read_csv("https://storage.googleapis.com/tf-datasets/titanic/train.csv")
titanic.head()

survived     sex   age  n_siblings_spouses  parch     fare  class     deck  \
0         0    male  22.0                   1      0   7.2500  Third  unknown   
1         1  female  38.0                   1      0  71.2833  First        C   
2         1  female  26.0                   0      0   7.9250  Third  unknown   
3         1  female  35.0                   1      0  53.1000  First        C   
4         0    male  28.0                   0      0   8.4583  Third  unknown   

   embark_town alone  
0  Southampton     n  
1    Cherbourg     n  
2  Southampton     y  
3  Southampton     n  
4   Queenstown     y

In [17]:
titanic_features = titanic.copy()
titanic_labels = titanic_features.pop('survived')

In [18]:
#symbolic input
input = tf.keras.Input(shape=(), dtype=tf.float32)

#Perform calculation with input
result = 2*input + 1

result


<KerasTensor: shape=(None,) dtype=float32 (created by layer 'tf.__operators__.add')>

In [19]:
calc = tf.keras.Model(inputs=input, outputs=result)

In [20]:
print(calc(1).numpy())
print(calc(2).numpy())

3.0
5.0


In [21]:
titanic_features.head()

inputs = {}

for name, column in titanic_features.items():
    dtype = column.dtype
    if dtype == object:
        dtype = tf.string
    else:
        dtype = tf.float32
        
    inputs[name] = tf.keras.Input(shape=(1,),name=name, dtype=dtype)

inputs        

{'sex': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'sex')>,
 'age': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'age')>,
 'n_siblings_spouses': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'n_siblings_spouses')>,
 'parch': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'parch')>,
 'fare': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'fare')>,
 'class': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'class')>,
 'deck': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'deck')>,
 'embark_town': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'embark_town')>,
 'alone': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'alone')>}

In [22]:
numeric_inputs = {name:input for name, input in inputs.items()
                  if input.dtype==tf.float32}

x = layers.Concatenate()(list(numeric_inputs.values()))
norm = layers.Normalization()
norm.adapt(np.array(titanic[numeric_inputs.keys()]))
all_numeric_inputs = norm(x)

all_numeric_inputs

<KerasTensor: shape=(None, 4) dtype=float32 (created by layer 'normalization_1')>

In [23]:
preprocessed_inputs = [all_numeric_inputs]
preprocessed_inputs

[<KerasTensor: shape=(None, 4) dtype=float32 (created by layer 'normalization_1')>]

In [24]:
for name, input in inputs.items():
  if input.dtype == tf.float32:
    continue

  lookup = layers.StringLookup(vocabulary=np.unique(titanic_features[name]))
  one_hot = layers.CategoryEncoding(max_tokens=lookup.vocab_size())

  x = lookup(input)
  x = one_hot(x)
  preprocessed_inputs.append(x)

In [25]:

pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [26]:
pip install pydot

Note: you may need to restart the kernel to use updated packages.


In [27]:
#konkatencaja p..cats i p...inputs
preprocessed_inputs_cat = layers.Concatenate()(preprocessed_inputs)

titanic_preprocessing = tf.keras.Model(inputs, preprocessed_inputs_cat)
tf.keras.utils.plot_model(model= titanic_preprocessing, rankdir="LR", dpi=72, show_shapes=True)

('You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) ', 'for plot_model/model_to_dot to work.')


In [29]:
titanic_features_dict = {name: np.array(value) 
                         for name, value in titanic_features.items()}
titanic_features_dict

{'sex': array(['male', 'female', 'female', 'female', 'male', 'male', 'female',
        'female', 'female', 'male', 'male', 'female', 'male', 'male',
        'female', 'female', 'male', 'male', 'female', 'male', 'male',
        'female', 'male', 'male', 'female', 'female', 'male', 'male',
        'male', 'male', 'female', 'female', 'female', 'male', 'female',
        'male', 'male', 'male', 'female', 'male', 'female', 'female',
        'male', 'male', 'female', 'male', 'male', 'male', 'female', 'male',
        'male', 'male', 'male', 'female', 'male', 'male', 'male', 'male',
        'male', 'male', 'male', 'male', 'female', 'male', 'male', 'female',
        'male', 'male', 'male', 'female', 'male', 'male', 'male', 'male',
        'male', 'male', 'female', 'male', 'female', 'male', 'male', 'male',
        'male', 'male', 'male', 'female', 'male', 'female', 'male',
        'female', 'male', 'male', 'male', 'male', 'male', 'male', 'female',
        'male', 'male', 'male', 'male', 'female',

In [30]:
features_dict = {name:values[:1] for name, values in titanic_features_dict.items()}
titanic_preprocessing(features_dict)

<tf.Tensor: shape=(1, 28), dtype=float32, numpy=
array([[-0.610415 ,  0.395198 , -0.4790527, -0.4974028,  0.       ,
         0.       ,  1.       ,  0.       ,  0.       ,  0.       ,
         1.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  1.       ,
         0.       ,  0.       ,  0.       ,  1.       ,  0.       ,
         0.       ,  1.       ,  0.       ]], dtype=float32)>

In [31]:
def titanic_model(preprocessed_head, inputs):
    body = tf.keras.Sequential([
        layers.Dense(64),
        layers.Dense(1)
    ])
    
    preprocessed_inputs = preprocessed_head(input)
    result = body(preprocessed_inputs)
    model = tf.keras.Model(inputs, result)
    
    model.compile(loss=tf.losses.BinaryCrossentropy(from_logits=True),
                  optimizer = tf.optimizers.Adam())
    
    titanic_model = titanic_model(titanic_preprocessing, inputs)